services:
  db:
    container_name: books-db
    image: postgres:17.2
    ports:
      - "5432:5432"
    command: postgres -c max_connections=500
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - books-network

  backend:
    container_name: books-backend
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/code/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - books-network
    command: cargo run

  frontend:
    container_name: books-frontend
    restart: always
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    ports:
      - "5173:5173"
    networks:
      - books-network
    command: npm run dev -- --host

  pgadmin:
    container_name: books-pgadmin
    restart: always
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    networks:
      - books-network

networks:
  books-network:
    driver: bridge
    external: true
    name: books-network
